hydra: 
  run:
    dir: outputs/${Experiment.name}/${Regulariser.name}/${now:%Y-%m-%d_%H%M%S}

defaults:
  - Experiment: Phantom
  - Function_1: LeastSquares
  - Function_2: IndicatorBox
  - Algorithm: ISTA
  - Hyperparameters: Hyperparameters 
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog